timeout: 2 # better for trying on real hardware

default_entry: 0

#wallpaper: boot():/boot/bg.jpg
term_background: FF000000
term_foreground: CCCCCC #234569
#term_font: boot():/boot/liminefont.f15
#term_font_size: 8x15
#term_font_spacing: 0
interface_resolution: 1280x720
interface_branding_colour: 9
interface_help_hidden: no
interface_help_colour: 7
interface_rotation: 0
interface_branding: emexOS v26AL.01.x (Limine 11.x.x)
editor_validation: no
verbose: yes
#serial: yes

# ----
# Dualslot kernel system
# ----

# entry0 default/ active
/Try emexOS
    protocol: limine
    cmdline: try
    #comment: Try emexOS as "live mode"

    kernel_path: boot():/boot/kernel_a.elf
    module_path: boot():/boot/initrd.cpio
    module_path: boot():/boot/initrdh.cpio
    module_path: boot():/boot/logo.bin
    module_path: boot():/boot/test.bin
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    kaslr: yes

# entry2
/install emexOS
    cmdline: install
    #comment: install emexOS to a specific partition, or the full disk (does NOT work)
    protocol: limine
    # the slot is A because the kernel A installs kernel B which isn't used
    kernel_path: boot():/boot/kernel_a.elf
    module_path: boot():/boot/initrd.cpio
    module_path: boot():/boot/initrdh.cpio
    module_path: boot():/boot/kernel_a.elf
    module_path: boot():/boot/logo.bin
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_path: boot():/boot/limine/limine-bios.sys
    kaslr: yes

# entry3
/emexOS gui98
    cmdline: try
    protocol: limine
    #comment: automatically boots into the GUI

    # the slot is A because the kernel A installs kernel B which isn't used
    kernel_path: boot():/boot/kernel_a.elf
    module_path: boot():/boot/initrd.cpio
    module_path: boot():/boot/initrdh.cpio
    module_path: boot():/boot/kernel_a.elf
    module_path: boot():/boot/logo.bin
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_path: boot():/boot/limine/limine-bios.sys
    kaslr: yes

# slot 2 for update
# entry3
/other
//[kernel] slot_entry=B
    protocol: limine
    cmdline: try
    cmdline: slot_b

    kernel_path: boot():/boot/kernel_b.elf
    module_path: boot():/boot/initrd.cpio
    module_path: boot():/boot/initrdh.cpio
    module_path: boot():/boot/logo.bin
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    kaslr: yes
//[kernel] slot_entry=C
    protocol: limine
    cmdline: backup
    cmdline: slot_c

    kernel_path: boot():/boot/kernel_b.elf
    module_path: boot():/boot/initrd.cpio
    module_path: boot():/boot/logo.bin
    module_path: boot():/boot/initrdh.cpio
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    kaslr: yes


# ----
# resolutions
# ----

#   resolution: 1920x1080x32
#   resolution: 2560x1440x32
#   resolution: 3840x2160x32
