CC      := x86_64-elf-gcc
LD      := x86_64-elf-ld
LIBC    := ../../libc
LIBS_D  := ../../libs

CFLAGS  := -ffreestanding -nostdlib -fno-builtin -fno-stack-protector \
           -fno-PIE -fno-pic -m64 -march=x86-64 -mno-sse -mno-sse2    \
           -mno-mmx -mno-red-zone -Wall -Wextra -std=gnu11            \
           -I$(LIBC)/include          \
           -I$(LIBS_D)/libdesktop     \
           -I$(LIBS_D)/libfont        \
           -I$(LIBS_D)/eXui           \
           -I$(LIBS_D)/libbmp         \
           -I$(LIBS_D)/libvad         \
           -I$(LIBS_D)/emxfb0

LDFLAGS := -nostdlib -static -no-pie -T ../../user.ld

LIBS    := $(LIBS_D)/eXui/libexui.a           \
           $(LIBS_D)/libdesktop/libdesktop.a  \
           $(LIBS_D)/libfont/libfont.a        \
           $(LIBS_D)/libbmp/libbmp.a          \
           $(LIBS_D)/libvad/libvad.a          \
           $(LIBS_D)/emxfb0/libemxfb0.a

all: libs clean sysinfo.elf

sysinfo.elf: sysinfo.o $(LIBC)/build/crt0.o $(LIBC)/build/libc.a $(LIBS)
	$(LD) $(LDFLAGS) $(LIBC)/build/crt0.o sysinfo.o $(LIBS) $(LIBC)/build/libc.a -o $@

sysinfo.o: sysinfo.c
	$(CC) $(CFLAGS) -c $< -o $@

$(LIBC)/build/crt0.o $(LIBC)/build/libc.a:
	$(MAKE) -C $(LIBC)

libs:
	$(MAKE) -C $(LIBS_D)/libfont
	$(MAKE) -C $(LIBS_D)/libdesktop
	$(MAKE) -C $(LIBS_D)/eXui
	$(MAKE) -C $(LIBS_D)/libbmp
	$(MAKE) -C $(LIBS_D)/libvad
	$(MAKE) -C $(LIBS_D)/emxfb0

clean:
	rm -f *.o sysinfo.elf

.PHONY: all libs clean